### ISSUE TITLE
Prevent using gzipped sequence file (or add gzip input support)

### ISSUE THREAD

**Issue by niemasd** [Niema-Lab/ViralWasm-Epi#3]
Right now, we don't support gzipped input sequence files, but I was able to provide one (I forgot), and it ran and crashed when I tried to run Minimap2 (but not descriptively). I think we can try to support gzipped input files in the future, but for now, we should prevent the user from running if they selected a gzipped file

**Comment by daniel-ji** [comment]
Hi Niema,

Thanks for letting me know! I've went ahead and added fasta gzip input support in commit 192a86 . Wasn't too bad to do at all! 

Best,
Daniel

**Comment by daniel-ji** [comment]
Hi Niema,

Thanks for letting me know! I've went ahead and added fasta gzip input support in commit 192a86e . Wasn't too bad to do at all!

Best,
Daniel

**Comment by niemasd** [comment]
Awesome, thank you!!
